<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function getFindAllQuery()
    {
        return $this->createQueryBuilder('b')
            ->join('b.category', 'c')
            ->leftJoin('b.tags', 't')
            ->getQuery();
    }
}
